GSOC-Organisations Page
COSH-NITK/cosh-website pull request #16
Opened 2024-02-22 13:35 UTC by marcdhi

# Patch Preview
![Screenshot 2024-02-22 at 18 58 42](https://github.com/COSH-NITK/cosh-website/assets/97223188/5c72198f-f13f-4fcb-9b0c-68da113933b5)
![Screenshot 2024-02-22 at 18 59 03](https://github.com/COSH-NITK/cosh-website/assets/97223188/a39f21df-eb3f-4d77-9d00-ae152f43b90b)

## Todo:

- [ ] Make Org Page Responsive with Filter Sidebar
- [ ] Read More button below filters to open a modal
- [ ] Org Cards should be clickable (& redirect them to Org Pages)
- [ ] Map People to Org

2024-02-23 05:08 UTC, mittal-parth requested changes

2024-02-23 05:08 UTC, mittal-parth commented on src/Components/OrgCard/OrganisationCard.jsx
> +    default_image = 'https://firebasestorage.googleapis.com/v0/b/cosh-website.appspot.com/o/COSH%20website%20assets%2FEvents%20images%2Fdefault-event-image.svg?alt=media&token=9756c350-dea2-42f4-a94d
Better to keep this in the public assets?

2024-02-23 05:08 UTC, mittal-parth commented on src/Components/OrgCard/OrganisationCard.jsx
> +                    {/* <p className='org-desc'>{organisation.desc || 'No description'}</p> */}
```suggestion
```

2024-02-23 05:08 UTC, mittal-parth commented on src/Components/OrgCard/OrganisationCard.jsx
> +                    <p className='org-tag'>{organisation.categories || 'Tag Not Specified'}</p>
Instead of showing the text 'Tag Not Specified', I think we should just not have the any tag.

2024-02-23 05:08 UTC, mittal-parth commented on src/Components/OrganisationsList/OrganisationsList.jsx
> +function OrganisationsList({ organisations, default_image = 'https://firebasestorage.googleapis.com/v0/b/cosh-website.appspot.com/o/COSH%20website%20assets%2FEvents%20images%2Fdefault-event-image.svg
Again, this link hardcoding is not a very good approach.
Either store this image in the public directory or (if its not possible to do that), define this constant somewhere else.

2024-02-23 05:08 UTC, mittal-parth commented on src/Components/OrganisationsList/OrganisationsList.jsx
> +            return values.includes(organisation[filter]);
Possible to convert this into a function?
Being repeated.

2024-02-23 05:08 UTC, mittal-parth commented on src/Pages/Organisation/Organisations.jsx
> +];
I hope all of this is just for testing. Adding a comment so that we an remove it before merging. Should come from Firebase.

2024-02-23 05:36 UTC, aadilkhalifa commented
I would suggest experimenting with some softer BG colors or replacing fill with border, for the organization card tags to make the them more subtle. The [visual hierarchy](https://www.nngroup.com/articles/visual-hierarchy-ux-definition/) should be such that the organization name is represented as the main element of the card.

2024-02-25 05:06 UTC, mittal-parth approved these changes

2024-03-28 17:57 UTC, closed without merging